apiVersion: v1
kind: Namespace
metadata:
  name: turkish-learning-prod
  labels:
    name: turkish-learning-prod
    environment: production
    app: turkish-learning-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: turkish-learning-prod
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: production-limits
  namespace: turkish-learning-prod
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
