apiVersion: v1
kind: ConfigMap
metadata:
  name: turkish-learning-config
  namespace: turkish-learning
data:
  # Database Configuration
  POSTGRES_DB: "turkish_learning"
  POSTGRES_USER: "postgres"
  POSTGRES_PORT: "5432"
  
  # Redis Configuration
  REDIS_PORT: "6379"
  
  # Backend Configuration
  NODE_ENV: "production"
  BACKEND_PORT: "3000"
  CORS_ORIGIN: "https://admin.turkishlearning.com"
  RATE_LIMIT_TTL: "60"
  RATE_LIMIT_LIMIT: "100"
  
  # AI Services Configuration
  AI_SERVICES_PORT: "8000"
  MAX_FILE_SIZE: "52428800"
  WORKERS: "4"
  
  # Admin Panel Configuration
  ADMIN_PANEL_PORT: "3000"
  NEXT_PUBLIC_API_URL: "https://api.turkishlearning.com/api/v1"
  NEXT_PUBLIC_AI_SERVICE_URL: "https://ai.turkishlearning.com/api/v1"
  NEXTAUTH_URL: "https://admin.turkishlearning.com"
  
  # Monitoring Configuration
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"
  FLOWER_PORT: "5555"

---
apiVersion: v1
kind: Secret
metadata:
  name: turkish-learning-secrets
  namespace: turkish-learning
type: Opaque
stringData:
  # Database Secrets
  POSTGRES_PASSWORD: "your-secure-postgres-password"
  
  # Redis Secrets
  REDIS_PASSWORD: "your-secure-redis-password"
  
  # JWT Secrets
  JWT_SECRET: "your-super-secret-jwt-key"
  JWT_REFRESH_SECRET: "your-super-secret-jwt-refresh-key"
  
  # NextAuth Secret
  NEXTAUTH_SECRET: "your-nextauth-secret"
  
  # AI API Keys
  OPENAI_API_KEY: "your-openai-api-key"
  HUGGINGFACE_API_KEY: "your-huggingface-api-key"
  
  # Monitoring Secrets
  GRAFANA_ADMIN_PASSWORD: "your-grafana-admin-password"
  GRAFANA_SECRET_KEY: "your-grafana-secret-key"
  FLOWER_BASIC_AUTH: "admin:your-flower-password"
  
  # External Services
  SENTRY_DSN: "your-sentry-dsn"
